name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      REPO:
        description: Kernel Repo
        default: 'rsuntk/android_kernel_asus_sdm660-4.19'
        required: true
      BRANCH:
        description: Kernel branch
        default: 'android-4.19-lts'
        required: true
      KSU:
        description: Add KernelSU support
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: secureEnvironment
    steps:
    - name: Get date
      id: rundate
      run: sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo "REPO_DATE=`date`" >> $GITHUB_OUTPUT
    
    - uses: actions/checkout@v4
      with:
        path: kernel_root
        repository: ${{ github.event.inputs.REPO }}
        ref: ${{ github.event.inputs.BRANCH }}
        show-progress: false
        fetch-depth: 1

    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 -y
        sudo aptitude install libssl-dev -y

    - name: Regen defconfig
      id: buildKernel
      run: |
        export IS_CI=true
        git clone https://github.com/rsuntk/${GITHUB_REPOSITORY#*/} ~/tmp_repo --single-branch
        mv ~/tmp_repo/build.sh .
        bash build.sh -r
        gitsha1=$(git rev-parse --short HEAD)
        buildDetails="`make kernelversion`-rsuntk-Ratibor-X01BD_`echo $gitsha1`-`date +'%Y%m%d%H%M%S'`" && echo "buildDetails=$buildDetails" >> $GITHUB_OUTPUT

    - name: Upload configs
      uses: actions/upload-artifact@v4
      with:
        name: Defconfig-${{ steps.buildKernel.outputs.buildDetails }}
        path: kernel_root/arch/arm64/configs/rsuntk-X01BD_defconfig

    - name: Build kernel
      run: |
        if [[ "${{ github.event.inputs.KSU }}" = "true" ]]; then
          curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
        fi
        bash ./build.sh
        if [ -e $(pwd)/out/.config ]; then
          mv out/.config out/defconfig
        fi
        # Reduce the size
        rm out/arch/arm64/boot/Image
      working-directory: kernel_root

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build-${{ steps.buildKernel.outputs.buildDetails }}
        path: kernel_root/out/arch/arm64/boot/*
        compression-level: 9

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-${{ steps.buildKernel.outputs.buildDetails }}
        path: kernel_root/AnyKernel3/*
        compression-level: 9

    - name: Cleanup useless files
      continue-on-error: true
      run: |
        rm out/vmlinux.o out/vmlinux out/System.map
      working-directory: kernel_root
